apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: frontend-policy
  namespace: online-boutique
spec:
  
  action: DENY
  rules:
  - from:
    - source:
        namespaces: ["online-boutique"]
    to:
    - operation:
        ports: ["80"]