apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: istio-tls-external-secret
  namespace: istio-ingress

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: gateway-tls
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt }}"
        tls.key: "{{ .key }}"

  data:
  - remoteRef:
      key: dev/istio-tls-key
    secretKey: key
  - remoteRef:
      key: dev/istio-tls-cert
    secretKey: crt