apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stripe-api-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  
  target:
    name: stripe-api-key

  data:
  - remoteRef:
      key: stripe-api-key
      property: stripe-key
    secretKey: stripe-key