apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: add-clustered-nodes
resources:
  - ../../../base
images:
  - name: phoenix-liveview-counter
    newName: 326347646211.dkr.ecr.us-east-2.amazonaws.com/phoenix-liveview-counter-tutorial
    newTag: preview-23d11c715ac8d886d6eef8b6ab89d16f4f4ca106
replicas:
  - name: counter
    count: 2
configMapGenerator:
  - name: counter-configmap
    behavior: merge
    envs:
      - ./.env
patches:
  - path: ingress-patches.yaml
    target:
      version: v1
      kind: Ingress
      name: counter-ingress
