apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../base
images:
  - name: phoenix-liveview-counter
    newName: 326347646211.dkr.ecr.us-east-2.amazonaws.com/phoenix-liveview-counter-tutorial
    newTag: 473141aed54493faa2e0600799b9f9af3e14dd29
replicas:
  - name: counter
    count: 2
configMapGenerator:
  - name: counter-configmap
    behavior: merge
    envs:
      - ./.env
patches:
  - path: istio-patches.yaml
    target:
      kind: VirtualService
      name: counter-ingress
