apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../base
images:
  - name: phoenix-liveview-counter
    newName: 326347646211.dkr.ecr.us-east-2.amazonaws.com/phoenix-liveview-counter-tutorial
    newTag: 02d7a96a7fdf64565e890cd88b709176e1f2f0f7
replicas:
  - name: counter
    count: 2
configMapGenerator:
  - name: counter-configmap
    behavior: merge
    envs:
      - ./.env
patches:
  - path: istio-patches.yaml
    target:
      kind: VirtualService
      name: counter-ingress
