apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: counter
  name: counter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: counter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: counter
    spec:
      containers:
      - name: liveview-counter
        # this is the value that's replaced in overlays
        image: phoenix-liveview-counter
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            configMapKeyRef:
              name: counter-configmap
              key: SECRET_KEY_BASE
        - name: PHX_HOST
          valueFrom:
            configMapKeyRef:
              name: counter-configmap
              key: PHX_HOST
        - name: ERL_AFLAGS
          valueFrom:
            configMapKeyRef:
              name: counter-configmap
              key: ERL_AFLAGS
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}