apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: counter-ingress
spec:
  hosts:
  - replace.with.patch.overlay
  gateways:
    - istio-ingress/istio-gateway
  http:
  - route:
    - destination:
      host: counter
      port:
        number: 80
    match:
      - uri:
        prefix: /