apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: itp-123
resources:
  - ../../../base_liveview_counter
images:
  - name: phoenix-liveview-counter
    newName: 326347646211.dkr.ecr.us-east-2.amazonaws.com/phoenix-liveview-counter-tutorial
    newTag: itp-123
replicas:
  - name: counter
    count: 2
configMapGenerator:
  - name: counter-configmap
    behavior: merge
    envs:
      - ./.env
patches:
  - path: ingress-patches.yaml
    target:
      version: v1
      kind: Ingress
      name: counter-ingress
