apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: global-cluster-state
resources:
  - ../../../base
images:
  - name: phoenix-liveview-counter
    newName: 326347646211.dkr.ecr.us-east-2.amazonaws.com/phoenix-liveview-counter-tutorial
    newTag: preview-1f0884dd4a17913e3ead616137677ff469dc739a
replicas:
  - name: counter
    count: 2
configMapGenerator:
  - name: counter-configmap
    behavior: merge
    envs:
      - ./.env
patches:
  - path: istio-patches.yaml
    target:
      kind: VirtualService
      name: counter-ingress
