apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# these need created first
- nodeport-constraint.yaml
- privileged-container-constraint.yaml
# these need created after constraints
- block-nodeport-services.yaml
# - block-privileged-containers.yaml
