apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# these need created first
- block-nodeport-services.yaml
- block-privileged-containers.yaml
# these need created before constraints that use them!
- nodeport-constraint.yaml
# - privileged-container-constraint.yaml
