apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mnesia-playground
resources:
  - ../../../base
images:
  - name: phoenix-liveview-counter
    newName: 326347646211.dkr.ecr.us-east-2.amazonaws.com/phoenix-liveview-counter-tutorial
    newTag: preview-058f0a1ea3dd71639f4188bd60502b15250bbd7a
replicas:
  - name: counter
    count: 2
configMapGenerator:
  - name: counter-configmap
    behavior: merge
    envs:
      - ./.env
patches:
  - path: istio-patches.yaml
    target:
      kind: VirtualService
      name: counter-ingress
