apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mnesia-playground
resources:
  - ../../../base
images:
  - name: phoenix-liveview-counter
    newName: 326347646211.dkr.ecr.us-east-2.amazonaws.com/phoenix-liveview-counter-tutorial
    newTag: preview-424ab90c69f5e7b497cfa20d20f00a397bd5a3e7
replicas:
  - name: counter
    count: 2
configMapGenerator:
  - name: counter-configmap
    behavior: merge
    envs:
      - ./.env
patches:
  - path: istio-patches.yaml
    target:
      kind: VirtualService
      name: counter-ingress
