apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter-ingress
spec:
  rules:
  - host: dev.tonyrudny.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: counter
            port:
              number: 80