name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Extract Service Name & Version
        run: |
          # Parse the service name from the payload
          service_name=${{ github.event.client_payload.service }}
          echo "Service Name: $service_name"
          
          # Parse the version name from the payload
          version=${{ github.event.client_payload.version }}
          echo "Version: $version"