name: Remove Preview Environment
# https://github.com/tonyrud/elixir-distributed-playground/blob/main/.github/workflows/deploy.yml

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: 'Sent by return-dispatch action(Optional)'
      branch_name:
        description: 'Input a branch name for the preview environment to remove'
        required: true
jobs:
  preview_env_trigger:
    name: 'Remove preview: ${{ github.event.inputs.branch_name }}'
    runs-on: ubuntu-latest

    steps:
      # Required for the return-dispatch action
      - name: Distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}
            
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Remove dir for the preview environment in /dev
        run: |
          branch_name=${{ inputs.branch_name }}
          rm -rf apps/liveview-counter/envs/dev/$branch_name

      - name: Commit Changes
        run: |
          branch_name=${{ inputs.branch_name }}

          git config --global user.name "Continuous Deployment Bot"
          git config --global user.email "cd-bot@users.noreply.github.com"

          git add .
          git commit -m "remove preview env: $branch_name"
          git push