name: Update Release Version
# Trigger the workflow on repository_dispatch event
# This happens from new images from app repo: 
# https://github.com/tonyrud/devsecops-online-boutique-app
# Also:
# https://github.com/tonyrud/elixir-distributed-playground/blob/main/.github/workflows/deploy.yml

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: 'Sent by return-dispatch action. Not required.'
      image_name:
        description: 'Input a service name (e.g., gcr-adservice)'
        required: true
      version:
        description: 'Input a version (e.g., v1.0.0 or commit SHA)'
        required: true
    
jobs:
  release_version_trigger:
    name: 'Update ${{ github.event.inputs.image_name }} to ${{ github.event.inputs.version }}'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Echo Service Name & Version
        run: |
          # Parse the service name from the payload
          image_name=${{ inputs.image_name }}
          echo "Service Name: $image_name"

          # Parse the version name from the payload
          version=${{ inputs.version }}
          echo "Version: $version"
      
      - name: Distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

      - name: Update image tag in dev/kustomization.yaml
        run: |
          image_name=${{ inputs.image_name }}
          version=${{ inputs.version }}

          # Update the image in the kustomization.yaml file
          sh scripts/update_image_counter_version.sh $image_name $version

      - name: Commit Changes
        run: |
          image_name=${{ inputs.image_name }}
          version=${{ inputs.version }}

          git config --global user.name "Continuous Deployment Bot"
          git config --global user.email "cd-bot@users.noreply.github.com"

          git add .
          git commit -m "Update $image_name to $version"
          git push