name: Update ArgoCD Release Version
# Trigger the workflow on repository_dispatch event
# This happens from new images from app repo: 
# https://github.com/tonyrud/devsecops-online-boutique-app

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: 'Sent by return-dispatch action. Not required.'
      service:
        description: 'Input a service name (e.g., gcr-adservice)'
        required: true
      version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true
    
jobs:
  release_version_trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Echo Service Name & Version
        run: |
          # Parse the service name from the payload
          service_name=${{ inputs.service }}
          echo "Service Name: $service_name"

          # Parse the version name from the payload
          version=${{ inputs.version }}
          echo "Version: $version"
      
      - name: Update Image in Kustomization
        run: |
          service_name=${{ inputs.service }}
          version=${{ inputs.version }}

          # Update the image in the kustomization.yaml file
          sh update_release_version.sh $service_name $version

      - name: Commit Changes
        run: |
          service_name=${{ inputs.service }}
          version=${{ inputs.version }}

          git config --global user.name "Continuous Deployment Bot"
          git config --global user.email "cd-bot@users.noreply.github.com"

          git add overlays/dev/kustomization.yaml
          git commit -m "Update $service_name to $version"
          git push